# Two Linux frontend nodes (Azure Arc-enabled servers).
[frontend]
uxus1sitaarc01 ansible_host=10.192.2.150
uxus1sitaarc02 ansible_host=10.192.2.149

[frontend:vars]
# Set to the SSH user on the nodes.
ansible_user=azureuser
# ansible_ssh_private_key_file=~/.ssh/id_rsa
